title: Home
icon: mdi:account-cowboy-hat
type: stack
views:
  - type: vertical
    cards:
      - type: custom:mushroom-vacuum-card
        entity: vacuum.the_idiot
        name: The Idiot
        commands:
          - on_off
          - start_pause
          - return_home
      - type: climate
        entity: climate.air_conditioning
  - type: vertical
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: action
            icon: mdi:lightbulb
            icon_color: '#ff0000'
            name: All Lights Off
            tap_action:
              action: call-service
              service: scene.turn_on
              target:
                entity_id: scene.lights_off
          - type: action
            icon: mdi:weather-sunny
            icon_color: '#33ffff'
            tap_action:
              action: call-service
              service: scene.turn_on
              target:
                entity_id: scene.work_morning
          - type: action
            icon: mdi:heat-wave
            icon_color: '#ffbb33'
            tap_action:
              action: call-service
              service: scene.turn_on
              target:
                entity_id: scene.evening
          - type: action
            icon: mdi:television
            icon_color: '#3344ff'
            tap_action:
              action: call-service
              service: scene.turn_on
              target:
                entity_id: scene.tv_time
          - type: action
            icon: mdi:gas-burner
            icon_color: '#eebbff'
            tap_action:
              action: call-service
              service: scene.turn_on
              target:
                entity_id: scene.warm_kitchen
          - type: action
            icon: mdi:chef-hat
            icon_color: '#ffffff'
            tap_action:
              action: call-service
              service: scene.turn_on
              target:
                entity_id: scene.cooking_time
          - type: action
            icon: mdi:power-socket
            icon_color: '#ff0000'
            name: Kitchen 3
            tap_action:
              action: toggle
              entity: switch.none_p300_kitchen_three
          - type: action
            icon: mdi:led-strip-variant
            icon_color: '#00ff00'
            name: Kitchen 1
            tap_action:
              action: toggle
              entity: switch.none_kitchen_one
